{
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.0"},
  "colab": {"provenance": []}
 },
 "cells": [

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🧠 ICT Market Maker Engine — Protocol v2.0\n",
    "## خوارزمية التوقع قبل التنفيذ | 6-Stage Decision System\n",
    "\n",
    "```\n",
    "Stage 1 → Draw on Liquidity    (DOL — أين يريد السعر أن يذهب؟)\n",
    "Stage 2 → SMT Divergence       (كشف التلاعب بين الأصول المترابطة)\n",
    "Stage 3 → Time Filter + Judas  (الوقت = شرط لا تفاوض فيه)\n",
    "Stage 4 → Fractal Drill-Down   (H1 → M15 → M5 — الدخول الجراحي)\n",
    "Stage 5 → PD Arrays + StdDev   (أولوية المناطق + الأهداف الخوارزمية)\n",
    "Stage 6 → Confidence Gate      (بوابة القرار — Score Matrix)\n",
    "```\n",
    "---\n",
    "> **للأغراض التعليمية فقط · ليس نصيحة مالية**"
   ]
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 1 — Installation\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "!pip install yfinance plotly pandas numpy pytz --quiet\n",
    "print('✅ Libraries installed')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 2 — Imports & Display Settings\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "import warnings; warnings.filterwarnings('ignore')\n",
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "from plotly.subplots import make_subplots\n",
    "from dataclasses import dataclass, field\n",
    "from typing import Optional, List, Tuple\n",
    "from datetime import datetime, time\n",
    "import pytz\n",
    "from IPython.display import display, HTML\n",
    "\n",
    "pd.set_option('display.float_format', '{:.4f}'.format)\n",
    "pd.set_option('display.max_columns', 25)\n",
    "pd.set_option('display.width', 140)\n",
    "\n",
    "# ── ANSI Colors for terminal logs ──\n",
    "class C:\n",
    "    RESET  = '\\033[0m'\n",
    "    BOLD   = '\\033[1m'\n",
    "    CYAN   = '\\033[96m'\n",
    "    GREEN  = '\\033[92m'\n",
    "    YELLOW = '\\033[93m'\n",
    "    RED    = '\\033[91m'\n",
    "    BLUE   = '\\033[94m'\n",
    "    PURPLE = '\\033[95m'\n",
    "    GRAY   = '\\033[90m'\n",
    "    WHITE  = '\\033[97m'\n",
    "\n",
    "def log(msg, color=C.WHITE, indent=0):\n",
    "    prefix = '  ' * indent\n",
    "    print(f'{color}{prefix}{msg}{C.RESET}')\n",
    "\n",
    "def section(title, color=C.CYAN):\n",
    "    w = 72\n",
    "    print(f'\\n{color}{\"═\"*w}')\n",
    "    print(f'  {title}')\n",
    "    print(f'{\"─\"*w}{C.RESET}')\n",
    "\n",
    "print('✅ Imports ready')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 3 — ⚙️ Configuration (Edit Here Only)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "# ── Primary Asset ──\n",
    "TICKER          = 'TSLA'      # الرمز الأساسي\n",
    "\n",
    "# ── SMT Correlated Asset (for divergence check) ──\n",
    "SMT_TICKER      = 'QQQ'       # الأصل المرتبط (QQQ, SPY, NVDA, MSFT...)\n",
    "\n",
    "# ── Timeframes ──\n",
    "HTF_INTERVAL    = '1d'        # High Time Frame: Daily\n",
    "MID_INTERVAL    = '1h'        # Mid Time Frame: H1\n",
    "EXEC_INTERVAL   = '15m'       # Execution TF: M15\n",
    "ENTRY_INTERVAL  = '5m'        # Entry TF: M5\n",
    "\n",
    "# ── Data Periods ──\n",
    "HTF_PERIOD      = '6mo'       # HTF data window\n",
    "EXEC_PERIOD     = '5d'        # Execution TF window (max 60d for intraday)\n",
    "\n",
    "# ── Stage 1: DOL Parameters ──\n",
    "SWING_LB        = 5           # Swing lookback (bars each side)\n",
    "HTF_CANDLES     = 100         # HTF candles to scan\n",
    "LIQUIDITY_TOUCHES = 2         # Min touches to count as liquidity pool\n",
    "\n",
    "# ── Stage 2: SMT Parameters ──\n",
    "SMT_WINDOW      = 20          # Candles for swing comparison\n",
    "SMT_TOLERANCE   = 0.003       # 0.3% tolerance for 'equal' swings\n",
    "\n",
    "# ── Stage 3: Killzone (Eastern Time) ──\n",
    "KILLZONES = {\n",
    "    'london_open':   (2,  0,  5,  0),   # 02:00 – 05:00 ET\n",
    "    'ny_open':       (7,  0, 10,  0),   # 07:00 – 10:00 ET\n",
    "    'silver_bullet': (10, 0, 11,  0),   # 10:00 – 11:00 ET  ← أعلى دقة\n",
    "    'london_close':  (10, 0, 12,  0),   # 10:00 – 12:00 ET\n",
    "}\n",
    "JUDAS_WINDOW_MIN = 30          # Minutes after open to watch for Judas\n",
    "\n",
    "# ── Stage 4: Fractal Parameters ──\n",
    "SWEEP_WICK_MIN  = 15.0        # Min wick % for sweep\n",
    "MSS_LOOKFORWARD = 20          # Bars to look for MSS after sweep\n",
    "FVG_LOOKBACK    = 10          # Bars around MSS to find FVG\n",
    "\n",
    "# ── Stage 5: Standard Deviation Levels ──\n",
    "STDDEV_LEVELS   = [0.5, 1.0, 2.0, 4.0]   # Expansion levels\n",
    "\n",
    "# ── Stage 6: Score Thresholds ──\n",
    "SCORE_A_PLUS    = 10          # A+ Grade\n",
    "SCORE_A         = 7           # A Grade\n",
    "SCORE_MIN       = 5           # Minimum to show\n",
    "\n",
    "print(f'🎯 Primary: {TICKER}  |  SMT Pair: {SMT_TICKER}')\n",
    "print(f'📊 HTF: {HTF_INTERVAL}  |  Exec: {EXEC_INTERVAL}  |  Entry: {ENTRY_INTERVAL}')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 4 — Data Classes\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "@dataclass\n",
    "class LiquidityLevel:\n",
    "    price: float\n",
    "    kind: str           # 'BSL' | 'SSL'\n",
    "    touches: int\n",
    "    formed_at: pd.Timestamp\n",
    "    timeframe: str\n",
    "    is_dol: bool = False\n",
    "\n",
    "@dataclass\n",
    "class SMTSignal:\n",
    "    direction: str      # 'bullish' | 'bearish'\n",
    "    asset1_swing: float\n",
    "    asset2_swing: float\n",
    "    detected_at: pd.Timestamp\n",
    "    description: str\n",
    "    score: int = 2\n",
    "\n",
    "@dataclass\n",
    "class TimeContext:\n",
    "    in_killzone: bool\n",
    "    zone_name: str\n",
    "    judas_detected: bool\n",
    "    judas_direction: str   # 'up' | 'down' | 'none'\n",
    "    score: int = 0\n",
    "\n",
    "@dataclass\n",
    "class SwingPoint:\n",
    "    index: int\n",
    "    timestamp: pd.Timestamp\n",
    "    price: float\n",
    "    kind: str           # 'high' | 'low'\n",
    "\n",
    "@dataclass\n",
    "class LiqSweep:\n",
    "    direction: str\n",
    "    swept_price: float\n",
    "    swept_at: pd.Timestamp\n",
    "    swept_idx: int\n",
    "    close_after: float\n",
    "    wick_pct: float\n",
    "    strength: str = field(init=False)\n",
    "    def __post_init__(self):\n",
    "        if self.wick_pct > 40: self.strength = 'STRONG'\n",
    "        elif self.wick_pct > 25: self.strength = 'MEDIUM'\n",
    "        else: self.strength = 'WEAK'\n",
    "\n",
    "@dataclass\n",
    "class StructureBreak:\n",
    "    kind: str           # 'MSS' | 'BOS'\n",
    "    direction: str      # 'bullish' | 'bearish'\n",
    "    break_price: float\n",
    "    broke_at: pd.Timestamp\n",
    "    candle_idx: int\n",
    "\n",
    "@dataclass\n",
    "class FVG:\n",
    "    direction: str\n",
    "    top: float\n",
    "    bottom: float\n",
    "    midpoint: float\n",
    "    formed_at: pd.Timestamp\n",
    "    candle_idx: int\n",
    "    size_pct: float\n",
    "    filled: bool = False\n",
    "\n",
    "@dataclass\n",
    "class PDArray:\n",
    "    kind: str           # 'breaker' | 'ob' | 'fvg' | 'sibi' | 'equilibrium'\n",
    "    direction: str      # 'bullish' | 'bearish'\n",
    "    top: float\n",
    "    bottom: float\n",
    "    midpoint: float\n",
    "    formed_at: pd.Timestamp\n",
    "    priority: int       # 1=highest, 5=lowest\n",
    "    timeframe: str\n",
    "\n",
    "@dataclass\n",
    "class StdDevTarget:\n",
    "    level: float        # 0.5, 1.0, 2.0, 4.0\n",
    "    price: float\n",
    "    label: str\n",
    "    is_tp: bool = True\n",
    "\n",
    "@dataclass\n",
    "class DecisionLog:\n",
    "    stage: str\n",
    "    finding: str\n",
    "    score_delta: int\n",
    "    reasoning: str\n",
    "    risk_note: str = ''\n",
    "\n",
    "@dataclass\n",
    "class TradeSetup:\n",
    "    ticker: str\n",
    "    bias: str           # 'long' | 'short'\n",
    "    entry: float\n",
    "    stop_loss: float\n",
    "    targets: List[StdDevTarget]\n",
    "    pd_array: PDArray\n",
    "    score: int\n",
    "    grade: str\n",
    "    decision_log: List[DecisionLog]\n",
    "    dol: Optional[LiquidityLevel]\n",
    "    smt: Optional[SMTSignal]\n",
    "    sweep: Optional[LiqSweep]\n",
    "    mss: Optional[StructureBreak]\n",
    "    fvg_entry: Optional[FVG]\n",
    "    time_ctx: Optional[TimeContext]\n",
    "    risk_summary: str = ''\n",
    "\n",
    "print('✅ Data classes ready')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 5 — Data Layer\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def fetch(ticker, period, interval):\n",
    "    df = yf.download(ticker, period=period, interval=interval,\n",
    "                     auto_adjust=True, progress=False)\n",
    "    if df.empty: raise ValueError(f'No data: {ticker}')\n",
    "    if isinstance(df.columns, pd.MultiIndex):\n",
    "        df.columns = df.columns.droplevel(1)\n",
    "    df = df[['Open','High','Low','Close','Volume']].dropna()\n",
    "    return df\n",
    "\n",
    "\n",
    "def detect_swings(df, lookback=5, n=100):\n",
    "    sl = df.iloc[-n:].copy().reset_index()\n",
    "    swings = []\n",
    "    def ts(i):\n",
    "        for c in ['Datetime','Date']:\n",
    "            if c in sl.columns: return pd.Timestamp(sl[c].iloc[i])\n",
    "        return sl.index[i]\n",
    "    for i in range(lookback, len(sl)-lookback):\n",
    "        wh = sl['High'].iloc[i-lookback:i+lookback+1]\n",
    "        wl = sl['Low'].iloc[i-lookback:i+lookback+1]\n",
    "        if sl['High'].iloc[i] == wh.max():\n",
    "            swings.append(SwingPoint(i, ts(i), float(sl['High'].iloc[i]), 'high'))\n",
    "        if sl['Low'].iloc[i] == wl.min():\n",
    "            swings.append(SwingPoint(i, ts(i), float(sl['Low'].iloc[i]), 'low'))\n",
    "    return _dedup(swings, lookback)\n",
    "\n",
    "\n",
    "def _dedup(swings, w):\n",
    "    def keep(pts, mode):\n",
    "        if not pts: return []\n",
    "        res, grp = [], [pts[0]]\n",
    "        for p in pts[1:]:\n",
    "            if abs(p.index - grp[-1].index) <= w: grp.append(p)\n",
    "            else:\n",
    "                res.append(max(grp, key=lambda x: x.price) if mode=='high'\n",
    "                           else min(grp, key=lambda x: x.price))\n",
    "                grp = [p]\n",
    "        res.append(max(grp, key=lambda x: x.price) if mode=='high'\n",
    "                   else min(grp, key=lambda x: x.price))\n",
    "        return res\n",
    "    h = keep([s for s in swings if s.kind=='high'], 'high')\n",
    "    l = keep([s for s in swings if s.kind=='low'],  'low')\n",
    "    return sorted(h + l, key=lambda x: x.index)\n",
    "\n",
    "\n",
    "print('✅ Data layer ready')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 6 — Stage 1: Draw on Liquidity (DOL)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def stage1_draw_on_liquidity(df_htf: pd.DataFrame,\n",
    "                              swings: List[SwingPoint],\n",
    "                              tolerance: float = 0.002) -> Tuple[List[LiquidityLevel], Optional[LiquidityLevel], str]:\n",
    "    \"\"\"\n",
    "    الهدف: تحديد المغناطيس السعري (DOL) قبل أي حركة.\n",
    "\n",
    "    المنطق:\n",
    "    1. رسم مستويات السيولة: قمم وقيعان HTF ذات لمسات متعددة\n",
    "    2. قياس 'الكثافة' = عدد المرات التي لامس فيها السعر المستوى\n",
    "    3. تحديد DOL = الأكثر كثافة في اتجاه التحيز الكبير\n",
    "    4. تأمين التحيز: السعر أسفل DOL → Long Bias / فوقه → Short Bias\n",
    "    \"\"\"\n",
    "    levels = []\n",
    "    current_price = float(df_htf['Close'].iloc[-1])\n",
    "\n",
    "    # ── بناء خريطة السيولة ──\n",
    "    highs = [s for s in swings if s.kind == 'high']\n",
    "    lows  = [s for s in swings if s.kind == 'low']\n",
    "\n",
    "    def count_touches(price, df, side, tol=tolerance):\n",
    "        \"\"\"كم مرة لامس السعر هذا المستوى؟ كلما زادت اللمسات = سيولة أكبر\"\"\"\n",
    "        count = 0\n",
    "        for i in range(len(df)):\n",
    "            if side == 'high':\n",
    "                if abs(float(df['High'].iloc[i]) - price) / price <= tol:\n",
    "                    count += 1\n",
    "            else:\n",
    "                if abs(float(df['Low'].iloc[i]) - price) / price <= tol:\n",
    "                    count += 1\n",
    "        return count\n",
    "\n",
    "    for h in highs:\n",
    "        touches = count_touches(h.price, df_htf, 'high')\n",
    "        if touches >= LIQUIDITY_TOUCHES:\n",
    "            levels.append(LiquidityLevel(\n",
    "                price=h.price, kind='BSL', touches=touches,\n",
    "                formed_at=h.timestamp, timeframe=HTF_INTERVAL\n",
    "            ))\n",
    "\n",
    "    for l in lows:\n",
    "        touches = count_touches(l.price, df_htf, 'low')\n",
    "        if touches >= LIQUIDITY_TOUCHES:\n",
    "            levels.append(LiquidityLevel(\n",
    "                price=l.price, kind='SSL', touches=touches,\n",
    "                formed_at=l.timestamp, timeframe=HTF_INTERVAL\n",
    "            ))\n",
    "\n",
    "    # ── إذا لم تُعثر على مستويات بلمسات كافية، خفض العتبة لضمان نتيجة ──\n",
    "    if not levels:\n",
    "        for h in highs[-5:]:\n",
    "            levels.append(LiquidityLevel(h.price, 'BSL', 1, h.timestamp, HTF_INTERVAL))\n",
    "        for l in lows[-5:]:\n",
    "            levels.append(LiquidityLevel(l.price, 'SSL', 1, l.timestamp, HTF_INTERVAL))\n",
    "\n",
    "    # ── تحديد DOL: المستوى الأكثر كثافة والأكثر قرباً في اتجاه التحيز ──\n",
    "    bsl_levels = sorted([l for l in levels if l.kind == 'BSL' and l.price > current_price],\n",
    "                         key=lambda x: (-x.touches, x.price))\n",
    "    ssl_levels = sorted([l for l in levels if l.kind == 'SSL' and l.price < current_price],\n",
    "                         key=lambda x: (-x.touches, -x.price))\n",
    "\n",
    "    # التحيز الكبير: إذا كان آخر close فوق منتصف نطاق HTF → هبوطي، وإلا صعودي\n",
    "    htf_high = float(df_htf['High'].max())\n",
    "    htf_low  = float(df_htf['Low'].min())\n",
    "    htf_mid  = (htf_high + htf_low) / 2\n",
    "    htf_bias = 'bearish' if current_price > htf_mid else 'bullish'\n",
    "\n",
    "    dol = None\n",
    "    if htf_bias == 'bearish' and ssl_levels:\n",
    "        dol = ssl_levels[0]\n",
    "    elif htf_bias == 'bullish' and bsl_levels:\n",
    "        dol = bsl_levels[0]\n",
    "    elif bsl_levels:\n",
    "        dol = bsl_levels[0]\n",
    "    elif ssl_levels:\n",
    "        dol = ssl_levels[0]\n",
    "\n",
    "    if dol:\n",
    "        dol.is_dol = True\n",
    "\n",
    "    # ── تحديد التحيز الفعلي بناءً على DOL ──\n",
    "    if dol:\n",
    "        bias = 'long'  if dol.price > current_price else 'short'\n",
    "    else:\n",
    "        bias = 'long' if htf_bias == 'bullish' else 'short'\n",
    "\n",
    "    return levels, dol, bias\n",
    "\n",
    "\n",
    "print('✅ Stage 1 (DOL) loaded')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 7 — Stage 2: SMT Divergence\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def stage2_smt_divergence(df1: pd.DataFrame, df2: pd.DataFrame,\n",
    "                           bias: str,\n",
    "                           window: int = SMT_WINDOW,\n",
    "                           tol: float = SMT_TOLERANCE) -> Tuple[Optional[SMTSignal], str]:\n",
    "    \"\"\"\n",
    "    كشف الانحراف الذكي بين أصلين مترابطين.\n",
    "\n",
    "    المنطق:\n",
    "    Bearish SMT: ASSET1 صنع Higher High بينما ASSET2 صنع Lower High\n",
    "                  → Market Maker رفع الأصل الأول لاصطياد البائعين\n",
    "    Bullish SMT: ASSET1 صنع Lower Low بينما ASSET2 صنع Higher Low\n",
    "                  → Market Maker خفض الأصل الأول لاصطياد المشترين\n",
    "\n",
    "    شرط التزامن: يجب أن تكون القمتان/القاعان في نفس النافذة الزمنية\n",
    "    \"\"\"\n",
    "    # محاذاة التواريخ\n",
    "    common = df1.index.intersection(df2.index)\n",
    "    if len(common) < window * 2:\n",
    "        return None, 'insufficient_data'\n",
    "\n",
    "    a1 = df1.loc[common].iloc[-window:]\n",
    "    a2 = df2.loc[common].iloc[-window:]\n",
    "\n",
    "    # ── مقارنة القمم للتحقق من Bearish SMT ──\n",
    "    a1_high_idx = a1['High'].idxmax()\n",
    "    a2_high_idx = a2['High'].idxmax()\n",
    "    a1_h = float(a1['High'].max())\n",
    "    a2_h = float(a2['High'].max())\n",
    "\n",
    "    # قمة سابقة (النصف الأول من النافذة)\n",
    "    half = window // 2\n",
    "    a1_prev_h = float(a1.iloc[:half]['High'].max())\n",
    "    a2_prev_h = float(a2.iloc[:half]['High'].max())\n",
    "    a1_cur_h  = float(a1.iloc[half:]['High'].max())\n",
    "    a2_cur_h  = float(a2.iloc[half:]['High'].max())\n",
    "\n",
    "    # ── مقارنة القيعان للتحقق من Bullish SMT ──\n",
    "    a1_prev_l = float(a1.iloc[:half]['Low'].min())\n",
    "    a2_prev_l = float(a2.iloc[:half]['Low'].min())\n",
    "    a1_cur_l  = float(a1.iloc[half:]['Low'].min())\n",
    "    a2_cur_l  = float(a2.iloc[half:]['Low'].min())\n",
    "\n",
    "    detected_at = a1.index[-1]\n",
    "\n",
    "    # Bearish SMT: A1 Higher High + A2 Lower High\n",
    "    if (a1_cur_h > a1_prev_h * (1 + tol) and\n",
    "        a2_cur_h < a2_prev_h * (1 - tol)):\n",
    "\n",
    "        pct_div = abs(a1_cur_h/a1_prev_h - a2_cur_h/a2_prev_h) * 100\n",
    "        sig = SMTSignal(\n",
    "            direction='bearish',\n",
    "            asset1_swing=a1_cur_h,\n",
    "            asset2_swing=a2_cur_h,\n",
    "            detected_at=detected_at,\n",
    "            description=(\n",
    "                f'{TICKER} صنع Higher High ({a1_cur_h:.2f} vs {a1_prev_h:.2f}) '\n",
    "                f'بينما {SMT_TICKER} صنع Lower High ({a2_cur_h:.2f} vs {a2_prev_h:.2f}). '\n",
    "                f'الانحراف: {pct_div:.2f}% — تلاعب صعودي لاصطياد البائعين.'\n",
    "            ),\n",
    "            score=2\n",
    "        )\n",
    "        return sig, 'bearish_divergence'\n",
    "\n",
    "    # Bullish SMT: A1 Lower Low + A2 Higher Low\n",
    "    if (a1_cur_l < a1_prev_l * (1 - tol) and\n",
    "        a2_cur_l > a2_prev_l * (1 + tol)):\n",
    "\n",
    "        pct_div = abs(a1_cur_l/a1_prev_l - a2_cur_l/a2_prev_l) * 100\n",
    "        sig = SMTSignal(\n",
    "            direction='bullish',\n",
    "            asset1_swing=a1_cur_l,\n",
    "            asset2_swing=a2_cur_l,\n",
    "            detected_at=detected_at,\n",
    "            description=(\n",
    "                f'{TICKER} صنع Lower Low ({a1_cur_l:.2f} vs {a1_prev_l:.2f}) '\n",
    "                f'بينما {SMT_TICKER} صنع Higher Low ({a2_cur_l:.2f} vs {a2_prev_l:.2f}). '\n",
    "                f'الانحراف: {pct_div:.2f}% — تلاعب هبوطي لاصطياد المشترين.'\n",
    "            ),\n",
    "            score=2\n",
    "        )\n",
    "        return sig, 'bullish_divergence'\n",
    "\n",
    "    # تطابق: تأكيد جزئي\n",
    "    if ((a1_cur_h > a1_prev_h and a2_cur_h > a2_prev_h) or\n",
    "        (a1_cur_l < a1_prev_l and a2_cur_l < a2_prev_l)):\n",
    "        return None, 'aligned_move'\n",
    "\n",
    "    return None, 'no_divergence'\n",
    "\n",
    "\n",
    "print('✅ Stage 2 (SMT) loaded')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 8 — Stage 3: Time Filter + Judas Detector\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def stage3_time_filter(df_exec: pd.DataFrame, bias: str) -> TimeContext:\n",
    "    \"\"\"\n",
    "    فلتر الوقت: السعر بدون وقت = تلاعب.\n",
    "\n",
    "    المنطق:\n",
    "    1. تحديد الـ Killzone الحالية (London/NY/Silver Bullet)\n",
    "    2. كشف Judas Swing: أول 30 دقيقة تتحرك عكس DOL = فخ\n",
    "    3. Silver Bullet (10-11 NY) = أعلى دقة تاريخية\n",
    "\n",
    "    أي نموذج خارج هذه النوافذ → score = 0 → تجاهل تام\n",
    "    \"\"\"\n",
    "    et_zone = pytz.timezone('US/Eastern')\n",
    "    utc_zone = pytz.utc\n",
    "\n",
    "    # آخر شمعة\n",
    "    last_ts = df_exec.index[-1]\n",
    "    if last_ts.tzinfo is None:\n",
    "        last_ts = last_ts.tz_localize('UTC')\n",
    "    last_et = last_ts.astimezone(et_zone)\n",
    "    last_time = last_et.time()\n",
    "\n",
    "    # ── فحص الـ Killzone ──\n",
    "    in_zone = False\n",
    "    zone_name = 'outside_killzone'\n",
    "\n",
    "    for name, (h1, m1, h2, m2) in KILLZONES.items():\n",
    "        start = time(h1, m1)\n",
    "        end   = time(h2, m2)\n",
    "        if start <= last_time <= end:\n",
    "            in_zone = True\n",
    "            zone_name = name\n",
    "            break\n",
    "\n",
    "    # ── رصد Judas Swing ──\n",
    "    judas_detected  = False\n",
    "    judas_direction = 'none'\n",
    "\n",
    "    # البحث في أول 30 دقيقة من NY Open\n",
    "    ny_open_hour = 7\n",
    "    judas_candles = []\n",
    "    for i in range(len(df_exec)):\n",
    "        ts = df_exec.index[i]\n",
    "        if ts.tzinfo is None: ts = ts.tz_localize('UTC')\n",
    "        t_et = ts.astimezone(et_zone)\n",
    "        t    = t_et.time()\n",
    "        if time(ny_open_hour, 0) <= t <= time(ny_open_hour, JUDAS_WINDOW_MIN):\n",
    "            judas_candles.append(i)\n",
    "\n",
    "    if judas_candles:\n",
    "        first_bar = df_exec.iloc[judas_candles[0]]\n",
    "        last_bar  = df_exec.iloc[judas_candles[-1]]\n",
    "        open_p  = float(first_bar['Open'])\n",
    "        close_p = float(last_bar['Close'])\n",
    "        judas_move = 'up' if close_p > open_p else 'down'\n",
    "\n",
    "        # Judas = تتحرك عكس التحيز الكبير\n",
    "        if (bias == 'long'  and judas_move == 'down') or \\\n",
    "           (bias == 'short' and judas_move == 'up'):\n",
    "            judas_detected  = True\n",
    "            judas_direction = judas_move\n",
    "\n",
    "    # ── حساب النقطة ──\n",
    "    score = 0\n",
    "    if in_zone:\n",
    "        score = 2\n",
    "        if zone_name == 'silver_bullet': score = 3   # مكافأة Silver Bullet\n",
    "    if judas_detected:\n",
    "        score = max(0, score - 1)   # تخفيض عند وجود Judas لم ينعكس بعد\n",
    "\n",
    "    return TimeContext(\n",
    "        in_killzone=in_zone,\n",
    "        zone_name=zone_name,\n",
    "        judas_detected=judas_detected,\n",
    "        judas_direction=judas_direction,\n",
    "        score=score\n",
    "    )\n",
    "\n",
    "\n",
    "print('✅ Stage 3 (Time Filter) loaded')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 9 — Stage 4: Fractal Drill-Down (H1 → M15 → M5)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def stage4_fractal_drill(df_h1: pd.DataFrame,\n",
    "                          df_m15: pd.DataFrame,\n",
    "                          df_m5: pd.DataFrame,\n",
    "                          bias: str) -> Tuple[Optional[LiqSweep], Optional[StructureBreak], Optional[FVG], int]:\n",
    "    \"\"\"\n",
    "    الدخول الجراحي: ربط 3 فريمات في سلسلة واحدة.\n",
    "\n",
    "    الشرط الوحيد للدخول:\n",
    "    H1 Sweep → M15 MSS (Internal Structure Break) → M5 FVG\n",
    "\n",
    "    أي حلقة مكسورة = لا دخول.\n",
    "    \"\"\"\n",
    "    # ── H1: البحث عن Sweep ──\n",
    "    swings_h1 = detect_swings(df_h1, lookback=SWING_LB, n=60)\n",
    "    h1_sweep = _find_latest_sweep(df_h1, swings_h1, bias, min_wick=SWEEP_WICK_MIN)\n",
    "\n",
    "    if not h1_sweep:\n",
    "        return None, None, None, 0\n",
    "\n",
    "    # ── M15: البحث عن MSS بعد الـ sweep ──\n",
    "    m15_mss = _find_mss_after_sweep(df_m15, h1_sweep, bias, lookforward=MSS_LOOKFORWARD)\n",
    "\n",
    "    if not m15_mss:\n",
    "        return h1_sweep, None, None, 1   # sweep فقط = نقطة جزئية\n",
    "\n",
    "    # ── M5: البحث عن FVG بعد الـ MSS ──\n",
    "    m5_fvg = _find_fvg_after_mss(df_m5, m15_mss, bias, lookback=FVG_LOOKBACK)\n",
    "\n",
    "    if not m5_fvg:\n",
    "        return h1_sweep, m15_mss, None, 2   # sweep + MSS = نقطتان\n",
    "\n",
    "    score = 2 if m5_fvg.filled else 3   # FVG نشط = أعلى نقطة\n",
    "    return h1_sweep, m15_mss, m5_fvg, score\n",
    "\n",
    "\n",
    "def _find_latest_sweep(df, swings, bias, min_wick=15.0):\n",
    "    sl = df.iloc[-80:].copy().reset_index()\n",
    "    sweeps = []\n",
    "    target_kind = 'high' if bias == 'short' else 'low'\n",
    "\n",
    "    def get_ts(row):\n",
    "        for c in ['Datetime','Date']:\n",
    "            if c in row.index: return pd.Timestamp(row[c])\n",
    "        return sl.index[0]\n",
    "\n",
    "    for i in range(1, len(sl)):\n",
    "        row = sl.iloc[i]\n",
    "        ch = float(row['High']); cl = float(row['Low'])\n",
    "        co = float(row['Open']); cc = float(row['Close'])\n",
    "        rng = max(ch - cl, 0.0001)\n",
    "        for sw in swings:\n",
    "            if sw.index >= i: continue\n",
    "            if sw.kind == 'high' and ch > sw.price and cc < sw.price:\n",
    "                wick = (ch - max(co, cc)) / rng * 100\n",
    "                if wick >= min_wick:\n",
    "                    sweeps.append(LiqSweep('buyside', sw.price, get_ts(row), i, cc, wick))\n",
    "            elif sw.kind == 'low' and cl < sw.price and cc > sw.price:\n",
    "                wick = (min(co, cc) - cl) / rng * 100\n",
    "                if wick >= min_wick:\n",
    "                    sweeps.append(LiqSweep('sellside', sw.price, get_ts(row), i, cc, wick))\n",
    "\n",
    "    if not sweeps: return None\n",
    "    # فلتر بالاتجاه\n",
    "    if bias == 'long':\n",
    "        relevant = [s for s in sweeps if s.direction == 'sellside']\n",
    "    else:\n",
    "        relevant = [s for s in sweeps if s.direction == 'buyside']\n",
    "    if not relevant: relevant = sweeps\n",
    "    return sorted(relevant, key=lambda x: x.swept_idx, reverse=True)[0]\n",
    "\n",
    "\n",
    "def _find_mss_after_sweep(df, sweep, bias, lookforward=20):\n",
    "    # نبحث في آخر 50 شمعة من M15\n",
    "    window = df.iloc[-50:]\n",
    "    if window.empty: return None\n",
    "\n",
    "    if bias == 'long':    # بعد sellside sweep نبحث عن BOS صعودي\n",
    "        lh = float(window['High'].iloc[0])\n",
    "        for i in range(1, min(lookforward, len(window))):\n",
    "            c = float(window['Close'].iloc[i])\n",
    "            h = float(window['High'].iloc[i])\n",
    "            if c > lh:\n",
    "                return StructureBreak('MSS', 'bullish', lh, window.index[i], i)\n",
    "            lh = max(lh, h)\n",
    "    else:                  # بعد buyside sweep نبحث عن BOS هبوطي\n",
    "        ll = float(window['Low'].iloc[0])\n",
    "        for i in range(1, min(lookforward, len(window))):\n",
    "            c = float(window['Close'].iloc[i])\n",
    "            l = float(window['Low'].iloc[i])\n",
    "            if c < ll:\n",
    "                return StructureBreak('MSS', 'bearish', ll, window.index[i], i)\n",
    "            ll = min(ll, l)\n",
    "    return None\n",
    "\n",
    "\n",
    "def _find_fvg_after_mss(df, mss, bias, lookback=10):\n",
    "    window = df.iloc[-30:]\n",
    "    if len(window) < 3: return None\n",
    "    best, best_sz = None, 0.0\n",
    "\n",
    "    for i in range(2, len(window)):\n",
    "        c1, c3 = window.iloc[i-2], window.iloc[i]\n",
    "        if mss.direction == 'bullish':\n",
    "            gb, gt = float(c1['High']), float(c3['Low'])\n",
    "            if gt > gb:\n",
    "                sz = (gt - gb) / gb * 100\n",
    "                if sz > best_sz:\n",
    "                    best_sz = sz\n",
    "                    best = FVG('bullish', gt, gb, round((gt+gb)/2,4), window.index[i], i, round(sz,3))\n",
    "        else:\n",
    "            gt, gb = float(c1['Low']), float(c3['High'])\n",
    "            if gt > gb:\n",
    "                sz = (gt - gb) / gb * 100\n",
    "                if sz > best_sz:\n",
    "                    best_sz = sz\n",
    "                    best = FVG('bearish', gt, gb, round((gt+gb)/2,4), window.index[i], i, round(sz,3))\n",
    "\n",
    "    if best:\n",
    "        for _, row in df.iloc[-10:].iterrows():\n",
    "            if best.direction == 'bullish' and float(row['Low']) <= best.bottom:\n",
    "                best.filled = True; break\n",
    "            if best.direction == 'bearish' and float(row['High']) >= best.top:\n",
    "                best.filled = True; break\n",
    "    return best\n",
    "\n",
    "\n",
    "print('✅ Stage 4 (Fractal Drill) loaded')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 10 — Stage 5: PD Arrays + Standard Deviation\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "# ── PD Array Priority Map ──\n",
    "PD_PRIORITY = {\n",
    "    'breaker':     1,\n",
    "    'ob':          2,\n",
    "    'fvg':         3,\n",
    "    'sibi':        4,\n",
    "    'equilibrium': 5,\n",
    "}\n",
    "\n",
    "\n",
    "def stage5_pd_arrays_and_stddev(\n",
    "    df_htf: pd.DataFrame,\n",
    "    df_exec: pd.DataFrame,\n",
    "    swings: List[SwingPoint],\n",
    "    sweep: Optional[LiqSweep],\n",
    "    mss: Optional[StructureBreak],\n",
    "    fvg: Optional[FVG],\n",
    "    bias: str\n",
    ") -> Tuple[Optional[PDArray], List[StdDevTarget], int]:\n",
    "    \"\"\"\n",
    "    المرحلة 5:\n",
    "    أ) بناء قائمة PD Arrays وترتيبها بالأولوية الصارمة\n",
    "    ب) حساب الأهداف بانحراف معياري من مدى التلاعب\n",
    "\n",
    "    قاعدة صارمة: إذا وُجد Breaker أو OB → تجاهل FVG كدخول.\n",
    "    الدخول دائماً من الأعلى أولوية.\n",
    "    \"\"\"\n",
    "    current = float(df_exec['Close'].iloc[-1])\n",
    "    pd_arrays = []\n",
    "\n",
    "    # ── بناء Order Blocks ──\n",
    "    for i in range(3, len(df_exec)-1):\n",
    "        row = df_exec.iloc[i]\n",
    "        prev = df_exec.iloc[i-1]\n",
    "        c = float(row['Close']); o = float(row['Open'])\n",
    "        p_c = float(prev['Close']); p_o = float(prev['Open'])\n",
    "        # Bullish OB: شمعة هبوطية تسبق ارتفاعاً قوياً\n",
    "        if bias == 'long' and c < o and p_c > p_o and p_c > c * 1.004:\n",
    "            pd_arrays.append(PDArray(\n",
    "                kind='ob', direction='bullish',\n",
    "                top=float(row['High']), bottom=float(row['Low']),\n",
    "                midpoint=(float(row['High'])+float(row['Low']))/2,\n",
    "                formed_at=df_exec.index[i], priority=2, timeframe=EXEC_INTERVAL\n",
    "            ))\n",
    "        # Bearish OB: شمعة صاعدة تسبق هبوطاً قوياً\n",
    "        elif bias == 'short' and c > o and p_c < p_o and p_c < c * 0.996:\n",
    "            pd_arrays.append(PDArray(\n",
    "                kind='ob', direction='bearish',\n",
    "                top=float(row['High']), bottom=float(row['Low']),\n",
    "                midpoint=(float(row['High'])+float(row['Low']))/2,\n",
    "                formed_at=df_exec.index[i], priority=2, timeframe=EXEC_INTERVAL\n",
    "            ))\n",
    "\n",
    "    # ── Breaker Blocks (OB مخترق يتحول إلى Breaker) ──\n",
    "    # شرط: OB تجاوزه السعر بعدها = Breaker (أعلى أولوية)\n",
    "    for pd in pd_arrays[:]:\n",
    "        if pd.kind == 'ob':\n",
    "            # فحص هل السعر اخترق الـ OB\n",
    "            later_data = df_exec[df_exec.index > pd.formed_at]\n",
    "            if not later_data.empty:\n",
    "                if pd.direction == 'bullish' and float(later_data['Low'].min()) < pd.bottom:\n",
    "                    pd.kind = 'breaker'; pd.priority = 1\n",
    "                elif pd.direction == 'bearish' and float(later_data['High'].max()) > pd.top:\n",
    "                    pd.kind = 'breaker'; pd.priority = 1\n",
    "\n",
    "    # ── إضافة FVG كـ PD Array ──\n",
    "    if fvg and not fvg.filled:\n",
    "        pd_arrays.append(PDArray(\n",
    "            kind='fvg', direction=fvg.direction,\n",
    "            top=fvg.top, bottom=fvg.bottom, midpoint=fvg.midpoint,\n",
    "            formed_at=fvg.formed_at, priority=3, timeframe=ENTRY_INTERVAL\n",
    "        ))\n",
    "\n",
    "    # ── إضافة Equilibrium ──\n",
    "    htf_h = float(df_htf['High'].iloc[-50:].max())\n",
    "    htf_l = float(df_htf['Low'].iloc[-50:].min())\n",
    "    eq = (htf_h + htf_l) / 2\n",
    "    pd_arrays.append(PDArray(\n",
    "        kind='equilibrium', direction=bias,\n",
    "        top=eq * 1.001, bottom=eq * 0.999, midpoint=eq,\n",
    "        formed_at=df_htf.index[-1], priority=5, timeframe=HTF_INTERVAL\n",
    "    ))\n",
    "\n",
    "    # ── اختيار أفضل PD Array ──\n",
    "    # فلتر: يجب أن تكون في الاتجاه الصحيح\n",
    "    valid = [p for p in pd_arrays\n",
    "             if (bias == 'long'  and p.direction in ['bullish', 'long']  and p.top < current) or\n",
    "                (bias == 'short' and p.direction in ['bearish', 'short'] and p.bottom > current)]\n",
    "\n",
    "    if not valid: valid = pd_arrays  # fallback\n",
    "\n",
    "    # ترتيب حسب الأولوية ثم أقرب للسعر\n",
    "    valid.sort(key=lambda x: (x.priority, abs(x.midpoint - current)))\n",
    "    best_pd = valid[0] if valid else None\n",
    "\n",
    "    # ── Standard Deviation Targets ──\n",
    "    # مدى التلاعب = نطاق آخر 20 شمعة (منطقة التجميع/التلاعب)\n",
    "    recent = df_exec.iloc[-20:]\n",
    "    manip_high = float(recent['High'].max())\n",
    "    manip_low  = float(recent['Low'].min())\n",
    "    manip_range = manip_high - manip_low\n",
    "\n",
    "    targets = []\n",
    "    label_map = {\n",
    "        0.5: 'Equilibrium (50%)',\n",
    "        1.0: 'TP1 — +1 StdDev',\n",
    "        2.0: 'TP2 — +2 StdDev (BSL/SSL)',\n",
    "        4.0: 'TP3 — +4 StdDev (Full Target)',\n",
    "    }\n",
    "\n",
    "    for lvl in STDDEV_LEVELS:\n",
    "        if bias == 'long':\n",
    "            price = manip_low + manip_range * lvl\n",
    "        else:\n",
    "            price = manip_high - manip_range * lvl\n",
    "        targets.append(StdDevTarget(\n",
    "            level=lvl, price=round(price, 4),\n",
    "            label=label_map.get(lvl, f'+{lvl} SD'),\n",
    "            is_tp=(lvl >= 1.0)\n",
    "        ))\n",
    "\n",
    "    # ── نقاط المرحلة 5 ──\n",
    "    score = 0\n",
    "    if best_pd:\n",
    "        score_map = {'breaker':2, 'ob':2, 'fvg':1, 'sibi':1, 'equilibrium':1}\n",
    "        score = score_map.get(best_pd.kind, 1)\n",
    "\n",
    "    return best_pd, targets, score\n",
    "\n",
    "\n",
    "print('✅ Stage 5 (PD Arrays + StdDev) loaded')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 11 — Stage 6: Confidence Gate + Decision Log Builder\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def stage6_confidence_gate(\n",
    "    dol: Optional[LiquidityLevel],\n",
    "    smt: Optional[SMTSignal],\n",
    "    smt_status: str,\n",
    "    time_ctx: TimeContext,\n",
    "    fractal_score: int,\n",
    "    sweep: Optional[LiqSweep],\n",
    "    mss: Optional[StructureBreak],\n",
    "    fvg: Optional[FVG],\n",
    "    pd_array: Optional[PDArray],\n",
    "    pd_score: int,\n",
    "    targets: List[StdDevTarget],\n",
    "    df_exec: pd.DataFrame,\n",
    "    bias: str,\n",
    "    ticker: str\n",
    ") -> Optional[TradeSetup]:\n",
    "    \"\"\"\n",
    "    بوابة القرار النهائية:\n",
    "    1. حساب Score الإجمالي\n",
    "    2. بناء Decision Log المفصل\n",
    "    3. تحديد Grade وإنتاج TradeSetup\n",
    "\n",
    "    Score Matrix:\n",
    "    DOL واضح            +2\n",
    "    SMT تأكيد/انحراف    +2\n",
    "    Killzone             +2 (+3 Silver Bullet)\n",
    "    Fractal complete     +3\n",
    "    PD Array strength    +2\n",
    "    Judas penalty        -2\n",
    "    ─────────────────────────\n",
    "    Max = 13 | A+: 10+ | A: 7-9 | B: 5-6 | Skip: <5\n",
    "    \"\"\"\n",
    "    log_entries: List[DecisionLog] = []\n",
    "    total_score = 0\n",
    "\n",
    "    current = float(df_exec['Close'].iloc[-1])\n",
    "\n",
    "    # ── Score 1: DOL ──\n",
    "    dol_score = 0\n",
    "    if dol:\n",
    "        dol_score = 2\n",
    "        total_score += dol_score\n",
    "        distance_pct = abs(dol.price - current) / current * 100\n",
    "        log_entries.append(DecisionLog(\n",
    "            stage='Stage 1 — DOL',\n",
    "            finding=f'DOL محدد: {dol.kind} @ {dol.price:.4f} ({dol.touches} لمسات)',\n",
    "            score_delta=dol_score,\n",
    "            reasoning=(\n",
    "                f'السعر الحالي {current:.4f} على بعد {distance_pct:.1f}% من المغناطيس. '\n",
    "                f'التحيز الكبير: {\"صعودي 🔺\" if bias==\"long\" else \"هبوطي 🔻\"}. '\n",
    "                f'السعر {\"أسفل DOL — يتجه للصعود\" if dol.price > current else \"فوق DOL — يتجه للهبوط\"}.'\n",
    "            ),\n",
    "            risk_note=f'إذا لم يصل السعر لـ {dol.price:.4f} خلال {dol.timeframe}، قد يكون DOL خاطئاً.'\n",
    "        ))\n",
    "    else:\n",
    "        log_entries.append(DecisionLog(\n",
    "            stage='Stage 1 — DOL',\n",
    "            finding='لم يُحدد DOL واضح',\n",
    "            score_delta=0,\n",
    "            reasoning='لا توجد سيولة HTF ذات كثافة كافية في اتجاه التحيز.',\n",
    "            risk_note='التحيز محسوب على أساس موقع السعر من HTF Range فقط.'\n",
    "        ))\n",
    "\n",
    "    # ── Score 2: SMT ──\n",
    "    smt_score = 0\n",
    "    if smt:\n",
    "        # تحقق من انسجام SMT مع bias\n",
    "        if (smt.direction == 'bullish' and bias == 'long') or \\\n",
    "           (smt.direction == 'bearish' and bias == 'short'):\n",
    "            smt_score = 2\n",
    "            smt_tag = '⚡ SMART MONEY DIVERGENCE DETECTED — REVERSAL IMMINENT'\n",
    "        else:\n",
    "            smt_score = -1  # SMT عكس التحيز = تحذير\n",
    "            smt_tag = '⚠️ SMT عكس التحيز الكبير — خطر التناقض'\n",
    "    elif smt_status == 'aligned_move':\n",
    "        smt_score = 1\n",
    "        smt_tag = '✓ الأصلان يتحركان بانسجام — تأكيد جزئي'\n",
    "    else:\n",
    "        smt_score = 0\n",
    "        smt_tag = '○ لا انحراف SMT — إشارة محايدة'\n",
    "\n",
    "    total_score += smt_score\n",
    "    log_entries.append(DecisionLog(\n",
    "        stage='Stage 2 — SMT Divergence',\n",
    "        finding=smt_tag,\n",
    "        score_delta=smt_score,\n",
    "        reasoning=smt.description if smt else f'العلاقة بين {ticker} و {SMT_TICKER}: {smt_status}.',\n",
    "        risk_note=(\n",
    "            'SMT ليس ضماناً للانعكاس. يجب التحقق مع Fractal قبل الدخول.'\n",
    "            if smt else 'غياب SMT يعني فقدان تأكيد إضافي من Smart Money.'\n",
    "        )\n",
    "    ))\n",
    "\n",
    "    # ── Score 3: Killzone & Judas ──\n",
    "    total_score += time_ctx.score\n",
    "    judas_note = ''\n",
    "    if time_ctx.judas_detected:\n",
    "        judas_note = (\n",
    "            f'⚠️ MANIPULATIVE MOVE IN PROGRESS — '\n",
    "            f'تحرك {\"صاعد\" if time_ctx.judas_direction==\"up\" else \"هابط\"} '\n",
    "            f'عكس التحيز في أول {JUDAS_WINDOW_MIN} دقيقة. '\n",
    "            f'انتظر الانعكاس قبل الدخول.'\n",
    "        )\n",
    "    zone_arabic = {\n",
    "        'london_open':   'London Open (02-05 ET)',\n",
    "        'ny_open':       'NY Open (07-10 ET)',\n",
    "        'silver_bullet': '🥈 Silver Bullet (10-11 ET) — أعلى دقة',\n",
    "        'london_close':  'London Close (10-12 ET)',\n",
    "        'outside_killzone': 'خارج نوافذ التداول'\n",
    "    }.get(time_ctx.zone_name, time_ctx.zone_name)\n",
    "\n",
    "    log_entries.append(DecisionLog(\n",
    "        stage='Stage 3 — Time Filter',\n",
    "        finding=f'النافذة الزمنية: {zone_arabic}',\n",
    "        score_delta=time_ctx.score,\n",
    "        reasoning=(\n",
    "            f'{\"داخل Killzone — النماذج هنا صالحة للتداول.\" if time_ctx.in_killzone else \"خارج Killzone — أي نموذج هنا هو ضجيج يجب تجاهله.\"}'\n",
    "        ),\n",
    "        risk_note=judas_note or 'لا يوجد Judas Swing مرصود في هذه الجلسة.'\n",
    "    ))\n",
    "\n",
    "    # ── Score 4: Fractal ──\n",
    "    total_score += fractal_score\n",
    "    fractal_parts = []\n",
    "    if sweep: fractal_parts.append(f'H1 Sweep ({sweep.direction} @ {sweep.swept_price:.4f})')\n",
    "    if mss:   fractal_parts.append(f'M15 MSS ({mss.direction} @ {mss.break_price:.4f})')\n",
    "    if fvg:   fractal_parts.append(f'M5 FVG ([{fvg.bottom:.4f}–{fvg.top:.4f}] {\"نشط\" if not fvg.filled else \"مملوء\"})')\n",
    "\n",
    "    fractal_chain = ' → '.join(fractal_parts) if fractal_parts else 'لا توجد سلسلة فراكتالية'\n",
    "    log_entries.append(DecisionLog(\n",
    "        stage='Stage 4 — Fractal Drill',\n",
    "        finding=fractal_chain,\n",
    "        score_delta=fractal_score,\n",
    "        reasoning=(\n",
    "            f'السلسلة الفراكتالية {\"مكتملة ✅\" if fractal_score >= 3 else \"جزئية ⚠️\" if fractal_score > 0 else \"غائبة ❌\"}. '\n",
    "            f'الدخول الجراحي يتطلب: H1 Sweep + M15 MSS + M5 FVG.'\n",
    "        ),\n",
    "        risk_note=(\n",
    "            f'FVG مملوء — دخول أقل دقة.' if (fvg and fvg.filled) else\n",
    "            'FVG غير مملوء — نقطة الدخول مثالية.' if fvg else\n",
    "            'لا FVG — الدخول سيكون عند OB أو Equilibrium.'\n",
    "        )\n",
    "    ))\n",
    "\n",
    "    # ── Score 5: PD Array ──\n",
    "    total_score += pd_score\n",
    "    if pd_array:\n",
    "        priority_label = {1:'Breaker Block (أعلى أولوية)',2:'Order Block',\n",
    "                          3:'Fair Value Gap',4:'SIBI/BISI',5:'Equilibrium (أدنى أولوية)'}\n",
    "        pd_label = priority_label.get(pd_array.priority, pd_array.kind)\n",
    "        log_entries.append(DecisionLog(\n",
    "            stage='Stage 5 — PD Arrays',\n",
    "            finding=f'{pd_label} | [{pd_array.bottom:.4f}–{pd_array.top:.4f}]',\n",
    "            score_delta=pd_score,\n",
    "            reasoning=(\n",
    "                f'أعلى منطقة أولوية متاحة: {pd_label}. '\n",
    "                f'سعر الدخول عند المنتصف: {pd_array.midpoint:.4f}. '\n",
    "                f'الأهداف محسوبة بانحراف معياري من مدى التلاعب.'\n",
    "            ),\n",
    "            risk_note=(\n",
    "                'Breaker Block: خطر الانتقام. إذا عادت الأسعار لكسر الـ Breaker → الاتجاه قد تغير.' if pd_array.priority == 1 else\n",
    "                'Order Block: خطر كسر الـ OB مجدداً إذا كان التحيز الكبير معاكساً.' if pd_array.priority == 2 else\n",
    "                'FVG: خطر ملء الفجوة قبل الانعكاس الحقيقي.' if pd_array.priority == 3 else\n",
    "                'Equilibrium: أضعف منطقة. يجب وجود تأكيدات إضافية.'\n",
    "            )\n",
    "        ))\n",
    "\n",
    "    # ── Judas Penalty ──\n",
    "    if time_ctx.judas_detected:\n",
    "        total_score = max(0, total_score - 2)\n",
    "        log_entries.append(DecisionLog(\n",
    "            stage='Judas Penalty',\n",
    "            finding='خصم Judas Swing (-2)',\n",
    "            score_delta=-2,\n",
    "            reasoning='تحرك تلاعبي عكس DOL في أول 30 دقيقة. انتظر الانعكاس الكامل.',\n",
    "            risk_note='لا تدخل أثناء Judas. انتظر إغلاق شمعة M5 فوق/تحت سعر الفتح.'\n",
    "        ))\n",
    "\n",
    "    # ── تحديد Grade ──\n",
    "    if total_score >= SCORE_A_PLUS:  grade = 'A+'\n",
    "    elif total_score >= SCORE_A:     grade = 'A'\n",
    "    elif total_score >= SCORE_MIN:   grade = 'B'\n",
    "    else:\n",
    "        grade = 'SKIP'\n",
    "\n",
    "    if grade == 'SKIP':\n",
    "        return None\n",
    "\n",
    "    # ── حساب Entry / SL ──\n",
    "    if pd_array and not fvg:\n",
    "        entry = pd_array.midpoint\n",
    "    elif fvg and not fvg.filled:\n",
    "        entry = fvg.midpoint\n",
    "    elif mss:\n",
    "        entry = mss.break_price\n",
    "    else:\n",
    "        entry = current\n",
    "\n",
    "    buf = entry * 0.003\n",
    "    if sweep:\n",
    "        sl = round(sweep.swept_price - buf, 4) if bias == 'long' \\\n",
    "             else round(sweep.swept_price + buf, 4)\n",
    "    else:\n",
    "        sl = round(entry * 0.985, 4) if bias == 'long' \\\n",
    "             else round(entry * 1.015, 4)\n",
    "\n",
    "    # ── ملخص المخاطر ──\n",
    "    risk_notes = [e.risk_note for e in log_entries if e.risk_note]\n",
    "    risk_summary = ' | '.join([r for r in risk_notes if r])\n",
    "\n",
    "    return TradeSetup(\n",
    "        ticker=ticker, bias=bias,\n",
    "        entry=round(entry, 4), stop_loss=sl,\n",
    "        targets=targets, pd_array=pd_array,\n",
    "        score=total_score, grade=grade,\n",
    "        decision_log=log_entries,\n",
    "        dol=dol, smt=smt, sweep=sweep,\n",
    "        mss=mss, fvg_entry=fvg,\n",
    "        time_ctx=time_ctx,\n",
    "        risk_summary=risk_summary\n",
    "    )\n",
    "\n",
    "\n",
    "print('✅ Stage 6 (Confidence Gate) loaded')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 12 — Decision Log Printer (الطباعة المفصلة)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def print_decision_log(setup: TradeSetup):\n",
    "    \"\"\"طباعة سجل القرار المفصل بتنسيق احترافي\"\"\"\n",
    "\n",
    "    GRADE_COLORS = {'A+': C.GREEN, 'A': C.CYAN, 'B': C.YELLOW, 'SKIP': C.RED}\n",
    "    GRADE_LABELS = {\n",
    "        'A+': '⭐ GRADE A+ — تنفيذ فوري',\n",
    "        'A':  '✅ GRADE A  — إعداد قوي',\n",
    "        'B':  '⚠️ GRADE B  — انتظر تأكيداً إضافياً',\n",
    "    }\n",
    "    gc = GRADE_COLORS.get(setup.grade, C.WHITE)\n",
    "\n",
    "    print(f'\\n{C.BOLD}{C.WHITE}{\"╔\" + \"═\"*72 + \"╗\"}{C.RESET}')\n",
    "    print(f'{C.BOLD}{C.CYAN}║  🧠 ICT MARKET MAKER ENGINE — DECISION LOG{\" \"*29}║{C.RESET}')\n",
    "    print(f'{C.BOLD}{C.WHITE}{\"╚\" + \"═\"*72 + \"╝\"}{C.RESET}')\n",
    "\n",
    "    # ── Header ──\n",
    "    bias_ar  = '🔺 شراء (LONG)' if setup.bias == 'long' else '🔻 بيع (SHORT)'\n",
    "    grade_lb = GRADE_LABELS.get(setup.grade, setup.grade)\n",
    "    print(f'{C.BOLD}{gc}  {grade_lb}   |   Score: {setup.score}/13{C.RESET}')\n",
    "    print(f'{C.GRAY}  الرمز: {setup.ticker}   |   الاتجاه: {bias_ar}   |   السعر الحالي تقريباً: {setup.entry:.4f}{C.RESET}')\n",
    "\n",
    "    # ── مسار القرار — كل مرحلة ──\n",
    "    section('📋 مسار القرار — 6 مراحل', C.BLUE)\n",
    "\n",
    "    for entry in setup.decision_log:\n",
    "        delta_str = f'+{entry.score_delta}' if entry.score_delta >= 0 else str(entry.score_delta)\n",
    "        delta_col = C.GREEN if entry.score_delta > 0 else (C.RED if entry.score_delta < 0 else C.GRAY)\n",
    "\n",
    "        print(f'\\n{C.BOLD}{C.PURPLE}  ▸ {entry.stage}{C.RESET}')\n",
    "        print(f'    {C.WHITE}النتيجة : {entry.finding}{C.RESET}')\n",
    "        print(f'    {C.GRAY}المنطق  : {entry.reasoning}{C.RESET}')\n",
    "        if entry.risk_note:\n",
    "            print(f'    {C.YELLOW}الخطر   : {entry.risk_note}{C.RESET}')\n",
    "        print(f'    {delta_col}النقاط  : {delta_str}{C.RESET}')\n",
    "\n",
    "    # ── جدول الصفقة ──\n",
    "    section('📊 خطة الصفقة النهائية', C.GREEN)\n",
    "\n",
    "    sl_dist = abs(setup.entry - setup.stop_loss)\n",
    "    print(f'  {C.CYAN}الدخول      : {setup.entry:.4f}{C.RESET}')\n",
    "    print(f'  {C.RED}وقف الخسارة : {setup.stop_loss:.4f}  (مسافة: {sl_dist:.4f}){C.RESET}')\n",
    "\n",
    "    for t in setup.targets:\n",
    "        if t.is_tp:\n",
    "            rr = round(abs(t.price - setup.entry) / sl_dist, 2) if sl_dist > 0 else 0\n",
    "            col = C.GREEN if t.level <= 2 else C.CYAN\n",
    "            print(f'  {col}{t.label:35} : {t.price:.4f}  (R:R {rr}){C.RESET}')\n",
    "\n",
    "    if setup.pd_array:\n",
    "        priority_names = {1:'Breaker Block ⚡',2:'Order Block',3:'FVG',4:'SIBI',5:'EQ'}\n",
    "        pd_name = priority_names.get(setup.pd_array.priority, setup.pd_array.kind)\n",
    "        print(f'\\n  {C.PURPLE}منطقة الدخول : {pd_name} [{setup.pd_array.bottom:.4f}–{setup.pd_array.top:.4f}]{C.RESET}')\n",
    "\n",
    "    # ── ملخص المخاطر ──\n",
    "    section('⚠️  ملخص المخاطر', C.YELLOW)\n",
    "    risk_entries = [e for e in setup.decision_log if e.risk_note]\n",
    "    for i, e in enumerate(risk_entries, 1):\n",
    "        print(f'  {C.YELLOW}[{i}] {e.risk_note}{C.RESET}')\n",
    "\n",
    "    # ── خلاصة المحرك بلغة طبيعية ──\n",
    "    section('💬 خلاصة المحرك — لماذا هذه الصفقة؟', C.CYAN)\n",
    "    _print_narrative(setup)\n",
    "\n",
    "    print(f'\\n{C.GRAY}{\"─\"*72}{C.RESET}\\n')\n",
    "\n",
    "\n",
    "def _print_narrative(setup: TradeSetup):\n",
    "    \"\"\"توليد خلاصة بلغة طبيعية تشرح منطق الصفقة\"\"\"\n",
    "    bias_ar = 'صعوداً' if setup.bias == 'long' else 'هبوطاً'\n",
    "    zone_ar = {\n",
    "        'london_open': 'London Open',\n",
    "        'ny_open': 'New York Open',\n",
    "        'silver_bullet': 'Silver Bullet (أعلى دقة)',\n",
    "        'london_close': 'London Close',\n",
    "        'outside_killzone': 'خارج النوافذ',\n",
    "    }.get(setup.time_ctx.zone_name if setup.time_ctx else '', 'غير محدد')\n",
    "\n",
    "    parts = []\n",
    "\n",
    "    if setup.dol:\n",
    "        parts.append(\n",
    "            f'أتوقع تحرك السعر {bias_ar} لأن DOL محدد عند '\n",
    "            f'{setup.dol.price:.4f} ({setup.dol.kind}) بكثافة {setup.dol.touches} لمسات'\n",
    "        )\n",
    "\n",
    "    if setup.smt:\n",
    "        parts.append(\n",
    "            f'الانحراف الذكي (SMT) بين {TICKER} و {SMT_TICKER} يؤكد أن '\n",
    "            f'Smart Money يتلاعب في الاتجاه {\"الصعودي\" if setup.smt.direction==\"bullish\" else \"الهبوطي\"}'\n",
    "        )\n",
    "\n",
    "    if setup.time_ctx and setup.time_ctx.in_killzone:\n",
    "        parts.append(f'الوقت هو {zone_ar} — النافذة الأكثر احتمالاً للتحرك الحقيقي')\n",
    "\n",
    "    if setup.sweep and setup.mss:\n",
    "        parts.append(\n",
    "            f'السحب الفراكتالي مكتمل: H1 sweep @ {setup.sweep.swept_price:.4f} '\n",
    "            f'← M15 MSS {setup.mss.direction} ← M5 FVG للدخول الجراحي'\n",
    "        )\n",
    "\n",
    "    if setup.pd_array:\n",
    "        pd_names = {1:'Breaker Block',2:'Order Block',3:'FVG',4:'SIBI',5:'Equilibrium'}\n",
    "        parts.append(\n",
    "            f'منطقة الدخول من {pd_names.get(setup.pd_array.priority, \"PD Array\")} '\n",
    "            f'(أولوية {setup.pd_array.priority}/5) — تجاهلت المناطق الأضعف'\n",
    "        )\n",
    "\n",
    "    # طباعة السرد\n",
    "    for p in parts:\n",
    "        print(f'  {C.WHITE}◆ {p}.{C.RESET}')\n",
    "\n",
    "    # تحذير إضافي\n",
    "    if setup.time_ctx and setup.time_ctx.judas_detected:\n",
    "        print(f'\\n  {C.RED}⚠️  تنبيه: Judas Swing مرصود — لا تدخل حتى يُكمل السعر انعكاسه!{C.RESET}')\n",
    "\n",
    "    if setup.fvg_entry and setup.fvg_entry.filled:\n",
    "        print(f'  {C.YELLOW}⚠️  الـ FVG مملوء جزئياً — الدخول من OB أو Equilibrium بدلاً منه.{C.RESET}')\n",
    "\n",
    "\n",
    "print('✅ Decision Log printer ready')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 13 — Master Run Function\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def run_market_maker_engine(ticker=TICKER, smt_ticker=SMT_TICKER,\n",
    "                             verbose=True):\n",
    "    \"\"\"\n",
    "    تشغيل المحرك الكامل لـ 6 مراحل.\n",
    "    يُرجع: TradeSetup أو None إذا لم تُستوفَ الشروط.\n",
    "    \"\"\"\n",
    "    section(f'🚀 ICT MARKET MAKER ENGINE | {ticker.upper()} vs {smt_ticker.upper()}', C.CYAN)\n",
    "\n",
    "    # ── جلب البيانات ──\n",
    "    log('جلب البيانات...', C.GRAY)\n",
    "    df_htf  = fetch(ticker, HTF_PERIOD, HTF_INTERVAL)\n",
    "    df_exec = fetch(ticker, EXEC_PERIOD, EXEC_INTERVAL)\n",
    "    df_m5   = fetch(ticker, '2d', ENTRY_INTERVAL)\n",
    "    df_smt  = fetch(smt_ticker, HTF_PERIOD, HTF_INTERVAL)\n",
    "    df_smt_exec = fetch(smt_ticker, EXEC_PERIOD, EXEC_INTERVAL)\n",
    "\n",
    "    log(f'HTF: {len(df_htf)} bars | Exec: {len(df_exec)} bars | M5: {len(df_m5)} bars', C.GRAY)\n",
    "\n",
    "    swings_htf  = detect_swings(df_htf, SWING_LB, HTF_CANDLES)\n",
    "\n",
    "    # ── Stage 1 ──\n",
    "    log('\\n▸ Stage 1: Draw on Liquidity...', C.BLUE)\n",
    "    liq_levels, dol, bias = stage1_draw_on_liquidity(df_htf, swings_htf)\n",
    "    log(f'  التحيز: {\"🔺 Long\" if bias==\"long\" else \"🔻 Short\"}  |  '\n",
    "        f'DOL: {dol.price:.4f} ({dol.kind})' if dol else '  DOL: لم يُحدد',\n",
    "        C.GREEN if bias=='long' else C.RED)\n",
    "\n",
    "    # ── Stage 2 ──\n",
    "    log('\\n▸ Stage 2: SMT Divergence...', C.BLUE)\n",
    "    smt_sig, smt_status = stage2_smt_divergence(df_htf, df_smt, bias)\n",
    "    if smt_sig:\n",
    "        log(f'  ⚡ SMT DETECTED: {smt_sig.direction.upper()}', C.YELLOW)\n",
    "        log(f'  {smt_sig.description[:80]}...', C.GRAY)\n",
    "    else:\n",
    "        log(f'  SMT Status: {smt_status}', C.GRAY)\n",
    "\n",
    "    # ── Stage 3 ──\n",
    "    log('\\n▸ Stage 3: Time Filter...', C.BLUE)\n",
    "    time_ctx = stage3_time_filter(df_exec, bias)\n",
    "    zone_str = '✅ داخل Killzone' if time_ctx.in_killzone else '❌ خارج Killzone'\n",
    "    log(f'  {zone_str}: {time_ctx.zone_name}', C.GREEN if time_ctx.in_killzone else C.RED)\n",
    "    if time_ctx.judas_detected:\n",
    "        log(f'  ⚠️ JUDAS SWING: تحرك {time_ctx.judas_direction} عكس التحيز — انتظر!', C.YELLOW)\n",
    "\n",
    "    # ── Stage 4 ──\n",
    "    log('\\n▸ Stage 4: Fractal Drill-Down...', C.BLUE)\n",
    "    sweep, mss, fvg, fractal_score = stage4_fractal_drill(df_exec, df_exec, df_m5, bias)\n",
    "    chain_parts = []\n",
    "    if sweep: chain_parts.append(f'H1 Sweep({sweep.direction})')\n",
    "    if mss:   chain_parts.append(f'M15 MSS({mss.direction})')\n",
    "    if fvg:   chain_parts.append(f'M5 FVG({\"active\" if not fvg.filled else \"filled\"})')\n",
    "    log(f'  Chain: {\" → \".join(chain_parts) or \"لا توجد سلسلة\"}  |  Score: {fractal_score}',\n",
    "        C.GREEN if fractal_score >= 3 else C.YELLOW)\n",
    "\n",
    "    # ── Stage 5 ──\n",
    "    log('\\n▸ Stage 5: PD Arrays + StdDev...', C.BLUE)\n",
    "    pd_array, targets, pd_score = stage5_pd_arrays_and_stddev(\n",
    "        df_htf, df_exec, swings_htf, sweep, mss, fvg, bias)\n",
    "    if pd_array:\n",
    "        log(f'  Best PD: {pd_array.kind} (priority {pd_array.priority}/5) '\n",
    "            f'@ [{pd_array.bottom:.4f}–{pd_array.top:.4f}]', C.PURPLE)\n",
    "    for t in targets:\n",
    "        if t.is_tp:\n",
    "            log(f'  {t.label}: {t.price:.4f}', C.GRAY)\n",
    "\n",
    "    # ── Stage 6 ──\n",
    "    log('\\n▸ Stage 6: Confidence Gate...', C.BLUE)\n",
    "    setup = stage6_confidence_gate(\n",
    "        dol, smt_sig, smt_status, time_ctx,\n",
    "        fractal_score, sweep, mss, fvg,\n",
    "        pd_array, pd_score, targets,\n",
    "        df_exec, bias, ticker\n",
    "    )\n",
    "\n",
    "    if setup is None:\n",
    "        log('\\n  ❌ SKIP — لا تستوفي الشروط الدنيا. المحرك يتجاهل هذا الإعداد.', C.RED)\n",
    "        return None, df_htf, df_exec, df_m5, liq_levels, swings_htf, dol\n",
    "\n",
    "    grade_col = {C.GREEN: ['A+'], C.CYAN: ['A'], C.YELLOW: ['B']}.get\n",
    "    log(f'\\n  ✅ GRADE {setup.grade} | Score: {setup.score}/13', C.GREEN)\n",
    "\n",
    "    # ── طباعة Decision Log ──\n",
    "    if verbose:\n",
    "        print_decision_log(setup)\n",
    "\n",
    "    return setup, df_htf, df_exec, df_m5, liq_levels, swings_htf, dol\n",
    "\n",
    "\n",
    "print('✅ Master engine ready')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 14 — 🚀 RUN THE ENGINE\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "result = run_market_maker_engine(TICKER, SMT_TICKER, verbose=True)\n",
    "setup, df_htf, df_exec, df_m5, liq_levels, swings_htf, dol = result"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 15 — 📊 Interactive Plotly Chart + Decision Log Panel\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "def build_mm_chart(df_plot, setup, liq_levels, swings, dol,\n",
    "                   ticker=TICKER, n_candles=80):\n",
    "    \"\"\"\n",
    "    شارت ICT Market Maker متكامل:\n",
    "    - Candlesticks + Volume\n",
    "    - BSL/SSL Liquidity Lines (خطوط أفقية بكثافة اللون)\n",
    "    - DOL (المغناطيس الرئيسي) — خط مميز\n",
    "    - Swing Highs/Lows (مثلثات)\n",
    "    - FVG Box (مستطيل ملون)\n",
    "    - Entry / SL / TP1-3 Levels\n",
    "    - StdDev Extension Lines\n",
    "    \"\"\"\n",
    "    df = df_plot.iloc[-n_candles:].copy()\n",
    "    x0, x1 = df.index[0], df.index[-1]\n",
    "\n",
    "    fig = make_subplots(\n",
    "        rows=2, cols=1, row_heights=[0.80, 0.20],\n",
    "        shared_xaxes=True, vertical_spacing=0.02,\n",
    "    )\n",
    "\n",
    "    # ── Candlesticks ──\n",
    "    fig.add_trace(go.Candlestick(\n",
    "        x=df.index,\n",
    "        open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'],\n",
    "        increasing=dict(line=dict(color='#26a69a', width=1), fillcolor='rgba(38,166,154,0.8)'),\n",
    "        decreasing=dict(line=dict(color='#ef5350', width=1), fillcolor='rgba(239,83,80,0.8)'),\n",
    "        name='OHLC', showlegend=False,\n",
    "    ), row=1, col=1)\n",
    "\n",
    "    # ── Volume ──\n",
    "    vcol = ['rgba(38,166,154,0.3)' if c >= o else 'rgba(239,83,80,0.3)'\n",
    "            for c, o in zip(df['Close'], df['Open'])]\n",
    "    fig.add_trace(go.Bar(\n",
    "        x=df.index, y=df['Volume'], marker_color=vcol, showlegend=False\n",
    "    ), row=2, col=1)\n",
    "\n",
    "    # ── BSL/SSL Liquidity Lines ──\n",
    "    bsl_drawn, ssl_drawn = set(), set()\n",
    "    for lv in liq_levels:\n",
    "        if lv.price < df['Low'].min() * 0.98 or lv.price > df['High'].max() * 1.02:\n",
    "            continue\n",
    "        is_dol = lv.is_dol\n",
    "        if lv.kind == 'BSL':\n",
    "            color = '#ff6b6b' if is_dol else 'rgba(255,100,100,0.5)'\n",
    "            width = 2.0 if is_dol else 0.8\n",
    "            dash  = 'solid' if is_dol else 'dot'\n",
    "            label = f'◆ DOL-BSL {lv.price:.2f} ({lv.touches}x)' if is_dol else f'BSL {lv.price:.2f}'\n",
    "        else:\n",
    "            color = '#51cf66' if is_dol else 'rgba(80,200,100,0.5)'\n",
    "            width = 2.0 if is_dol else 0.8\n",
    "            dash  = 'solid' if is_dol else 'dot'\n",
    "            label = f'◆ DOL-SSL {lv.price:.2f} ({lv.touches}x)' if is_dol else f'SSL {lv.price:.2f}'\n",
    "\n",
    "        fig.add_shape(type='line', x0=x0, y0=lv.price, x1=x1, y1=lv.price,\n",
    "                      line=dict(color=color, width=width, dash=dash), row=1, col=1)\n",
    "        if is_dol or lv.touches >= 3:\n",
    "            fig.add_annotation(x=x1, y=lv.price, text=f'  {label}',\n",
    "                               xanchor='left', showarrow=False,\n",
    "                               font=dict(size=9, color=color, family='monospace'),\n",
    "                               bgcolor='rgba(13,17,23,0.8)',\n",
    "                               bordercolor=color, borderwidth=1, borderpad=3,\n",
    "                               row=1, col=1)\n",
    "\n",
    "    # ── Swing Points ──\n",
    "    sh = [s for s in swings if s.kind=='high' and s.timestamp >= x0]\n",
    "    sl_pts = [s for s in swings if s.kind=='low'  and s.timestamp >= x0]\n",
    "    if sh:\n",
    "        fig.add_trace(go.Scatter(\n",
    "            x=[s.timestamp for s in sh], y=[s.price*1.002 for s in sh],\n",
    "            mode='markers', marker=dict(symbol='triangle-down', size=9,\n",
    "                color='rgba(239,83,80,0.85)'),\n",
    "            name='Swing H', hovertemplate='SH: %{y:.4f}<extra></extra>'\n",
    "        ), row=1, col=1)\n",
    "    if sl_pts:\n",
    "        fig.add_trace(go.Scatter(\n",
    "            x=[s.timestamp for s in sl_pts], y=[s.price*0.998 for s in sl_pts],\n",
    "            mode='markers', marker=dict(symbol='triangle-up', size=9,\n",
    "                color='rgba(38,166,154,0.85)'),\n",
    "            name='Swing L', hovertemplate='SL: %{y:.4f}<extra></extra>'\n",
    "        ), row=1, col=1)\n",
    "\n",
    "    # ── Trade Levels (if setup exists) ──\n",
    "    if setup:\n",
    "        def add_level(price, color, dash, label, width=1.8):\n",
    "            fig.add_shape(type='line', x0=x0, y0=price, x1=x1, y1=price,\n",
    "                          line=dict(color=color, width=width, dash=dash),\n",
    "                          row=1, col=1)\n",
    "            fig.add_annotation(x=x1, y=price, text=f'  ◀ {label}: {price:.4f}',\n",
    "                               xanchor='left', showarrow=False,\n",
    "                               font=dict(size=10, color=color, family='monospace'),\n",
    "                               bgcolor='rgba(13,17,23,0.85)',\n",
    "                               bordercolor=color, borderwidth=1, borderpad=4,\n",
    "                               row=1, col=1)\n",
    "\n",
    "        add_level(setup.entry,     '#00b4d8', 'solid', 'ENTRY', 2.2)\n",
    "        add_level(setup.stop_loss, '#ef5350', 'dot',   'SL',    1.5)\n",
    "\n",
    "        tp_colors = ['#26a69a', '#4caf50', '#8bc34a']\n",
    "        for i, t in enumerate([t for t in setup.targets if t.is_tp][:3]):\n",
    "            add_level(t.price, tp_colors[i], 'dash', f'TP{i+1} (+{t.level}σ)', 1.5)\n",
    "\n",
    "        # ── FVG Box ──\n",
    "        if setup.fvg_entry:\n",
    "            fvg = setup.fvg_entry\n",
    "            fill = 'rgba(0,180,216,0.07)' if not fvg.filled else 'rgba(100,100,100,0.05)'\n",
    "            border = 'rgba(0,180,216,0.4)' if not fvg.filled else 'rgba(100,100,100,0.3)'\n",
    "            fvg_x0 = fvg.formed_at if fvg.formed_at >= x0 else x0\n",
    "            fig.add_shape(type='rect', x0=fvg_x0, y0=fvg.bottom, x1=x1, y1=fvg.top,\n",
    "                          fillcolor=fill, line=dict(color=border, width=1), row=1, col=1)\n",
    "            fig.add_annotation(x=fvg_x0, y=(fvg.top+fvg.bottom)/2,\n",
    "                               text=f'  FVG {\"✅\" if not fvg.filled else \"⚠️\"}',\n",
    "                               xanchor='left', showarrow=False,\n",
    "                               font=dict(size=9, color='#00b4d8', family='monospace'),\n",
    "                               bgcolor='rgba(13,17,23,0.7)', row=1, col=1)\n",
    "\n",
    "        # ── Sweep arrow ──\n",
    "        if setup.sweep:\n",
    "            sw = setup.sweep\n",
    "            sw_x = sw.swept_at if sw.swept_at >= x0 else x0\n",
    "            sw_color = '#ef5350' if sw.direction=='buyside' else '#26a69a'\n",
    "            sw_ay = -40 if sw.direction=='buyside' else 40\n",
    "            fig.add_annotation(x=sw_x, y=sw.swept_price,\n",
    "                               ax=0, ay=sw_ay,\n",
    "                               arrowhead=2, arrowcolor=sw_color,\n",
    "                               arrowsize=1.2, arrowwidth=2,\n",
    "                               text=f'{\"⬇\" if sw.direction==\"buyside\" else \"⬆\"} Sweep',\n",
    "                               font=dict(size=9, color=sw_color, family='monospace'),\n",
    "                               bgcolor='rgba(13,17,23,0.8)',\n",
    "                               bordercolor=sw_color, borderwidth=1, borderpad=3,\n",
    "                               row=1, col=1)\n",
    "\n",
    "        # ── Info Badge ──\n",
    "        grade_sym = {'A+': '⭐⭐⭐', 'A': '⭐⭐', 'B': '⭐'}.get(setup.grade, '')\n",
    "        bias_sym  = '🔺 LONG' if setup.bias == 'long' else '🔻 SHORT'\n",
    "        badge = (f'<b>{bias_sym}</b><br>'\n",
    "                 f'Grade: {setup.grade} {grade_sym}<br>'\n",
    "                 f'Score: {setup.score}/13<br>'\n",
    "                 f'R:R ≈ {round(abs(setup.targets[1].price - setup.entry) / max(abs(setup.entry - setup.stop_loss), 0.01), 1) if len(setup.targets) > 1 else \"—\"}')\n",
    "        fig.add_annotation(\n",
    "            x=df.index[4], y=float(df['High'].max()) * 0.995,\n",
    "            text=badge, showarrow=False, align='left',\n",
    "            font=dict(size=11, color='#e8eaed', family='monospace'),\n",
    "            bgcolor='rgba(13,17,23,0.88)',\n",
    "            bordercolor='#2a4060', borderwidth=1, borderpad=8,\n",
    "            row=1, col=1\n",
    "        )\n",
    "\n",
    "    # ── Layout ──\n",
    "    grade_str = f' | GRADE {setup.grade} | Score {setup.score}/13' if setup else ''\n",
    "    fig.update_layout(\n",
    "        height=680,\n",
    "        template='plotly_dark',\n",
    "        paper_bgcolor='#0d1117',\n",
    "        plot_bgcolor='#0d1117',\n",
    "        font=dict(family='monospace', color='#8b949e', size=11),\n",
    "        margin=dict(l=10, r=160, t=50, b=10),\n",
    "        xaxis_rangeslider_visible=False,\n",
    "        hovermode='x unified',\n",
    "        title=dict(\n",
    "            text=f'<b>{ticker.upper()}</b> — ICT Market Maker Engine{grade_str}  |  {HTF_INTERVAL}',\n",
    "            font=dict(size=13, color='#58a6ff', family='monospace'), x=0.01\n",
    "        ),\n",
    "        hoverlabel=dict(bgcolor='#161b22', font=dict(family='monospace', size=11)),\n",
    "        legend=dict(orientation='h', x=0, y=1.02, bgcolor='rgba(0,0,0,0)',\n",
    "                    font=dict(size=10))\n",
    "    )\n",
    "    for row in [1, 2]:\n",
    "        fig.update_xaxes(gridcolor='#21262d', showgrid=True,\n",
    "                         tickfont=dict(size=10, color='#484f58'),\n",
    "                         zerolinecolor='#21262d', row=row, col=1)\n",
    "        fig.update_yaxes(gridcolor='#21262d', showgrid=True,\n",
    "                         tickfont=dict(size=10, color='#484f58'),\n",
    "                         side='right', row=row, col=1)\n",
    "    return fig\n",
    "\n",
    "\n",
    "# ── رسم الشارت ──\n",
    "fig = build_mm_chart(df_htf, setup, liq_levels, swings_htf, dol)\n",
    "fig.show()\n",
    "print('📊 الشارت يعرض HTF مع كل مستويات السيولة والصفقة.')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 16 — 📋 Pandas Trade Table (جدول الصفقات المفصل)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "if setup:\n",
    "    current_p = float(df_exec['Close'].iloc[-1])\n",
    "    sl_dist   = abs(setup.entry - setup.stop_loss)\n",
    "\n",
    "    # ── جدول المستويات ──\n",
    "    rows = []\n",
    "    rows.append({'المستوى': 'وقف الخسارة (SL)', 'السعر': setup.stop_loss,\n",
    "                 'المسافة': round(abs(setup.entry - setup.stop_loss), 4),\n",
    "                 'R:R': '—', 'الوصف': 'وراء منطقة الـ sweep'})\n",
    "    rows.append({'المستوى': 'الدخول (ENTRY)', 'السعر': setup.entry,\n",
    "                 'المسافة': 0, 'R:R': '1:1 ref',\n",
    "                 'الوصف': f'{setup.pd_array.kind if setup.pd_array else \"PD Array\"} midpoint'})\n",
    "\n",
    "    for t in setup.targets:\n",
    "        if t.is_tp and sl_dist > 0:\n",
    "            rr = round(abs(t.price - setup.entry) / sl_dist, 2)\n",
    "            rows.append({\n",
    "                'المستوى': t.label, 'السعر': t.price,\n",
    "                'المسافة': round(abs(t.price - setup.entry), 4),\n",
    "                'R:R': f'1:{rr}',\n",
    "                'الوصف': f'+{t.level} StdDev من مدى التلاعب'\n",
    "            })\n",
    "\n",
    "    trade_df = pd.DataFrame(rows)\n",
    "\n",
    "    # حساب P&L بالسعر الحالي\n",
    "    pnl_pts = (current_p - setup.entry) * (1 if setup.bias=='long' else -1)\n",
    "    pnl_pct = pnl_pts / setup.entry * 100\n",
    "\n",
    "    # ── طباعة ──\n",
    "    section('📋 جدول الصفقة — ICT Market Maker Engine', C.GREEN)\n",
    "    print(f'\\n  الرمز    : {setup.ticker}  |  الاتجاه: {\"🔺 Long\" if setup.bias==\"long\" else \"🔻 Short\"}')\n",
    "    print(f'  الجودة   : {setup.grade}   |  Score: {setup.score}/13')\n",
    "    print(f'  السعر الحالي: {current_p:.4f}  |  '\n",
    "          f'P&L: {\"+\" if pnl_pct>=0 else \"\"}{pnl_pct:.2f}% ({pnl_pts:+.4f})')\n",
    "\n",
    "    if setup.dol:\n",
    "        print(f'  DOL المستهدف: {setup.dol.price:.4f} ({setup.dol.kind}, {setup.dol.touches} لمسات)')\n",
    "\n",
    "    print(f'\\n{trade_df.to_string(index=False)}')\n",
    "\n",
    "    # ── حفظ ──\n",
    "    trade_df.to_csv(f'ict_mm_{TICKER}_{HTF_INTERVAL}.csv', index=False, encoding='utf-8-sig')\n",
    "    print(f'\\n  💾 محفوظ: ict_mm_{TICKER}_{HTF_INTERVAL}.csv')\n",
    "\n",
    "    # ── جدول Decision Log ──\n",
    "    section('📝 ملخص مراحل القرار', C.BLUE)\n",
    "    log_rows = []\n",
    "    for e in setup.decision_log:\n",
    "        log_rows.append({\n",
    "            'المرحلة': e.stage,\n",
    "            'النتيجة': e.finding[:50],\n",
    "            'النقاط': f'{e.score_delta:+d}',\n",
    "        })\n",
    "    log_df = pd.DataFrame(log_rows)\n",
    "    print(f'\\n{log_df.to_string(index=False)}')\n",
    "    print(f'\\n  ── Score الإجمالي: {setup.score}/13 | Grade: {setup.grade}')\n",
    "\n",
    "else:\n",
    "    print(f'{C.RED}❌ لا توجد إعدادات تستوفي الحد الأدنى للنقاط ({SCORE_MIN}).{C.RESET}')\n",
    "    print(f'{C.YELLOW}  جرّب: تخفيض SWEEP_WICK_MIN، توسيع EXEC_PERIOD، أو تغيير SMT_TICKER.{C.RESET}')"
   ],
   "outputs": [],
   "execution_count": null
  },

  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# ═══════════════════════════════════════════════════════════════\n",
    "# CELL 17 — تحليل رموز متعددة دفعة واحدة (Batch Mode)\n",
    "# ═══════════════════════════════════════════════════════════════\n",
    "\n",
    "WATCHLIST = [\n",
    "    ('AAPL', 'QQQ'),\n",
    "    ('NVDA', 'QQQ'),\n",
    "    ('TSLA', 'QQQ'),\n",
    "    # ('2222.SR', 'VTIP'),   # أرامكو\n",
    "    # ('EURUSD=X', 'DX-Y.NYB'),  # فوركس\n",
    "]\n",
    "\n",
    "section('🔍 BATCH MODE — مسح قائمة المراقبة', C.CYAN)\n",
    "\n",
    "batch_results = []\n",
    "for (tkr, smt_tkr) in WATCHLIST:\n",
    "    try:\n",
    "        res = run_market_maker_engine(tkr, smt_tkr, verbose=False)\n",
    "        s = res[0]\n",
    "        if s:\n",
    "            batch_results.append({\n",
    "                'الرمز': tkr, 'الزوج SMT': smt_tkr,\n",
    "                'الاتجاه': '🔺 Long' if s.bias=='long' else '🔻 Short',\n",
    "                'Grade': s.grade, 'Score': f'{s.score}/13',\n",
    "                'الدخول': s.entry, 'SL': s.stop_loss,\n",
    "                'TP1': s.targets[1].price if len(s.targets)>1 else '—',\n",
    "                'DOL': s.dol.price if s.dol else '—',\n",
    "                'SMT': '✅' if s.smt else '—',\n",
    "                'Fractal': '✅' if (s.sweep and s.mss) else '⚠️' if s.sweep else '❌',\n",
    "            })\n",
    "        else:\n",
    "            batch_results.append({\n",
    "                'الرمز': tkr, 'الزوج SMT': smt_tkr,\n",
    "                'الاتجاه': '—', 'Grade': 'SKIP', 'Score': '<5',\n",
    "                'الدخول': '—', 'SL': '—', 'TP1': '—',\n",
    "                'DOL': '—', 'SMT': '—', 'Fractal': '—'\n",
    "            })\n",
    "    except Exception as e:\n",
    "        print(f'{C.RED}  ⚠️ خطأ في {tkr}: {e}{C.RESET}')\n",
    "\n",
    "if batch_results:\n",
    "    batch_df = pd.DataFrame(batch_results)\n",
    "    print(f'\\n{batch_df.to_string(index=False)}')\n",
    "    batch_df.to_csv('ict_batch_scan.csv', index=False, encoding='utf-8-sig')\n",
    "    print(f'\\n  💾 ict_batch_scan.csv')"
   ],
   "outputs": [],
   "execution_count": null
  }

 ]
}
